### ISSUE TITLE
About the requests and guesses used on the client side (even if it requires manually modifying the client)

### ISSUE THREAD

**Issue by hope140** [Protected/EmbyParty#1]
Hello, when I was looking for a solution to watch movies with my girlfriend in the community, I found your solution, which made me very excited.

This has been a problem that has bothered me for a long time. I have tried many methods: [videotogether](https://github.com/VideoTogether/VideoTogether) (only usable on web pages), [syncplay](https://github.com/Syncplay/syncplay) (which I am currently using, but this limits us to Windows, although it is indeed the best solution I've found before encountering your project), and jellyfin (which only has a web version and often has issues, and the developer of the jellyfin community's related functions is no longer around). Your solution really made me feel a ray of hope. 

However, from your communication with the official staff in the community, I feel that you might be planning to abandon the feasibility of non-web ends. I am an outsider, just interested, and after looking at your directory structure and description, I found it somewhat similar to a [plugin](https://github.com/Shurelol/Emby.CustomCssJS/blob/main/src/README.md) I have seen before . The author's project can only be effective on the web if the client is not manually modified, and it requires adding to the system\dashboard-ui\modules directory. 

So I wonder if your project is also like this. If so, could you please indicate in the upcoming description file which files need to be operated on in what way to achieve the same effect as the web version on the client? I am looking forward to your reply!

English is not my native language, so I used a translation tool for this message. If there are any awkward or hard-to-understand parts, please bear with me. If you have any questions, I will try to reply as soon as I see them.

**Comment by hope140** [comment]
I found that this plugin has an English version of the readme, thank you for your trouble.

https://github.com/Shurelol/Emby.CustomCssJS/blob/main/src/README_EN.md

**Comment by Protected** [comment]
Hello. The change you need to make is described [here](https://emby.media/community/index.php?/topic/133445-emby-party-a-watch-party-solution-for-the-emby-web-client/), but this might change in the near future as I'm looking for a better way.

**Comment by hope140** [comment]
OK, thank you so much for sharing, I will try and feedback after work
