### ISSUE TITLE
No button appears after installing and inserting.

### ISSUE THREAD

**Issue by fandong1993** [Protected/EmbyParty#3]
hi, there

 after installing the plugin and inserting the code, no button appears. Can you help me with that?

**Comment by Protected** [comment]
Did you completely clear your browser cache before refreshing?

**Comment by fandong1993** [comment]
Yes, and I also opened a private tab, but no help.

**Comment by Protected** [comment]
Just to be clear, the plugin is actually running? Did you restart the server? Is it listed in the list of plugins in the settings section?

Are there any errors for it in the server log (prefix Party: ?)

Are there any related errors for appheader or partyheader in the browser console? Press ctrl+shift+i or f12 to open the browser console and be sure to refresh.

**Comment by fandong1993** [comment]
Thanks for your prompt response:
1. it is loading according to the logs, but I have no idea whether it is running. It appears in my plugins list. The code after inserting is 
![image](https://github.com/user-attachments/assets/56994c77-c6dc-425a-865e-44331663af65)

2. I restart my server many times.

3 Messages about Party in logs is like
`2024-11-16 12:04:25.556 Info App: Loading EmbyParty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/emby/plugins/EmbyParty.dll` and `Error App: Error in EmbyParty.EntryPoint
	*** Error Report ***
	Version: 4.8.10.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Linux version 5.16.0-0.bpo.4-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2
	Framework: .NET 6.0.31
	OS/Process: x64/x64
	Runtime: opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 6
	Data path: /var/lib/emby
	Application path: /opt/emby-server/system
	System.UnauthorizedAccessException: System.UnauthorizedAccessException: Access to the path '/opt/emby-server/system/dashboard-ui/modules/embyparty' is denied.
	 ---> System.IO.IOException: Permission denied
	   --- End of inner exception stack trace ---
	   at System.IO.FileSystem.CreateDirectory(String fullPath)
	   at System.IO.Directory.CreateDirectory(String path)
	   at EmbyParty.Plugin.ExtractResources()
	   at EmbyParty.EntryPoint.Run()
	   at Emby.Server.Implementations.ApplicationHost.RunEntryPoints(IEnumerable entryPoints, Boolean isBeforeStartup)
	Source: System.Private.CoreLib
	TargetSite: Void CreateDirectory(System.String)
	InnerException: System.IO.IOException: Permission denied
	Source: 
	TargetSite: ` 
and `System.IO.DirectoryNotFoundException: System.IO.DirectoryNotFoundException: Could not find a part of the path '/opt/emby-server/system/dashboard-ui/modules/embyparty/partyheader.js'.` 
4. Errors in the chrome console are:
![image](https://github.com/user-attachments/assets/77896b91-dcf5-4e98-8e64-0a7b780bdbe5)

**Comment by fandong1993** [comment]
Thanks a lot for your help！
I have tackled the problems, and the reason is the privilege of dir of emby.

**Comment by bscholer** [comment]
I was running into this same issue when running the [`lscr.io/linuxserver/emby:version-4.8.10.0`](https://hub.docker.com/r/linuxserver/emby) image on UnRAID.

Exec-ing into the running container and running `chmod -R 777 /app/emby`, followed by a couple restarts of the container seems to make the error go away. 

_I know this isn't good practice, but it got the job done. And it's in it's own container anyway so meh._

And yes, it seems like clearing the **entire** browser cache is necessary. It wasn't working when just clearing the single page's cache.

Excited to play around with this!

**Comment by Protected** [comment]
Well, the error was clearly there in the logs! Thank you for the additional contribution bscholer.

**Comment by gothdawid** [comment]
I fixed the permission issues by changing the owner for the "modules/embyparty" directory and maunaly uploading the missing files tp the "modules/embyparty/*" directory from GitHub.

Now I have this problem:

```
	
2025-01-14 02:36:48.493 Error App: Error in EmbyParty.EntryPoint
	*** Error Report ***
	Version: 4.8.10.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 6.8.12-5-pve (build@proxmox) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-5
	Framework: .NET 6.0.31
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 20
	Data path: /config
	Application path: /system
	System.ArgumentException: System.ArgumentException: The host part could not be converted to an IP address. (Parameter 'url')
	   at WebSocketSharp.Server.WebSocketServer..ctor(String url)
	   at EmbyParty.PartyManager.Run()
	   at EmbyParty.EntryPoint.Run()
	   at Emby.Server.Implementations.ApplicationHost.RunEntryPoints(IEnumerable`1 entryPoints, Boolean isBeforeStartup)
	Source: websocket-sharp
	TargetSite: Void .ctor(System.String)
```

**Comment by Protected** [comment]
If you have a new problem you might want to open a new issue!

**Comment by gothdawid** [comment]
I also don't have an embyparty button.
